//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobizAdmin.Resources.Create {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Create {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Create() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobizAdmin.Resources.Create.Create", typeof(Create).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appDate.
        /// </summary>
        public static string appDate {
            get {
                return ResourceManager.GetString("appDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie.
        /// </summary>
        public static string Categorie {
            get {
                return ResourceManager.GetString("Categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories Count.
        /// </summary>
        public static string Categories_Count {
            get {
                return ResourceManager.GetString("Categories_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Id.
        /// </summary>
        public static string Category_Id {
            get {
                return ResourceManager.GetString("Category_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time Order.
        /// </summary>
        public static string Date_Time_Order {
            get {
                return ResourceManager.GetString("Date_Time_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time PickUp.
        /// </summary>
        public static string Date_Time_PickUp {
            get {
                return ResourceManager.GetString("Date_Time_PickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        public static string Defaults {
            get {
                return ResourceManager.GetString("Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defDate.
        /// </summary>
        public static string defDate {
            get {
                return ResourceManager.GetString("defDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Count.
        /// </summary>
        public static string Details_Count {
            get {
                return ResourceManager.GetString("Details_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endDate.
        /// </summary>
        public static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EurKm.
        /// </summary>
        public static string EurKm {
            get {
                return ResourceManager.GetString("EurKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EurMinDrive.
        /// </summary>
        public static string EurMinDrive {
            get {
                return ResourceManager.GetString("EurMinDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EurMinimum.
        /// </summary>
        public static string EurMinimum {
            get {
                return ResourceManager.GetString("EurMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EurMinWait.
        /// </summary>
        public static string EurMinWait {
            get {
                return ResourceManager.GetString("EurMinWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kms.
        /// </summary>
        public static string Kms {
            get {
                return ResourceManager.GetString("Kms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxPax.
        /// </summary>
        public static string MaxPax {
            get {
                return ResourceManager.GetString("MaxPax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes Drive.
        /// </summary>
        public static string Minutes_Drive {
            get {
                return ResourceManager.GetString("Minutes_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes Wait.
        /// </summary>
        public static string Minutes_Wait {
            get {
                return ResourceManager.GetString("Minutes Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pax.
        /// </summary>
        public static string Pax {
            get {
                return ResourceManager.GetString("Pax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code.
        /// </summary>
        public static string Promo_Code {
            get {
                return ResourceManager.GetString("Promo Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates Categories.
        /// </summary>
        public static string Rates_Categories {
            get {
                return ResourceManager.GetString("Rates_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates Details.
        /// </summary>
        public static string Rates_Details {
            get {
                return ResourceManager.GetString("Rates_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates Details Id.
        /// </summary>
        public static string Rates_Details_Id {
            get {
                return ResourceManager.GetString("Rates_Details_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates Details VerNum.
        /// </summary>
        public static string Rates_Details_VerNum {
            get {
                return ResourceManager.GetString("Rates_Details_VerNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string Select_Language {
            get {
                return ResourceManager.GetString("Select_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service.
        /// </summary>
        public static string Select_Service {
            get {
                return ResourceManager.GetString("Select_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service Rate.
        /// </summary>
        public static string Select_Service_Rate {
            get {
                return ResourceManager.GetString("Select_Service_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceId.
        /// </summary>
        public static string ServiceId {
            get {
                return ResourceManager.GetString("ServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceName.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate.
        /// </summary>
        public static string Simulate {
            get {
                return ResourceManager.GetString("Simulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets Count.
        /// </summary>
        public static string Targets_Count {
            get {
                return ResourceManager.GetString("Targets_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verNum.
        /// </summary>
        public static string verNum {
            get {
                return ResourceManager.GetString("verNum", resourceCulture);
            }
        }
    }
}
