//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobizAdmin.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServicesText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServicesText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobizAdmin.Resources.Services.ServicesText", typeof(ServicesText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiKey.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppDate.
        /// </summary>
        public static string AppDate {
            get {
                return ResourceManager.GetString("AppDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Details.
        /// </summary>
        public static string Back_to_Details {
            get {
                return ResourceManager.GetString("Back_to_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string Back_to_List {
            get {
                return ResourceManager.GetString("Back_to_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Service.
        /// </summary>
        public static string Create_Service {
            get {
                return ResourceManager.GetString("Create_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Service Details.
        /// </summary>
        public static string Create_Service_Details {
            get {
                return ResourceManager.GetString("Create_Service_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateServiceRate.
        /// </summary>
        public static string Create_Service_Rate {
            get {
                return ResourceManager.GetString("Create_Service_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefDate.
        /// </summary>
        public static string DefDate {
            get {
                return ResourceManager.GetString("DefDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service.
        /// </summary>
        public static string Edit_Service {
            get {
                return ResourceManager.GetString("Edit_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EurKm.
        /// </summary>
        public static string EurKm {
            get {
                return ResourceManager.GetString("EurKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EurMinDrive.
        /// </summary>
        public static string EurMinDrive {
            get {
                return ResourceManager.GetString("EurMinDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EurMinimum.
        /// </summary>
        public static string EurMinimum {
            get {
                return ResourceManager.GetString("EurMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EurMinWait.
        /// </summary>
        public static string EurMinWait {
            get {
                return ResourceManager.GetString("EurMinWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexo.
        /// </summary>
        public static string Lexo {
            get {
                return ResourceManager.GetString("Lexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxPax.
        /// </summary>
        public static string MaxPax {
            get {
                return ResourceManager.GetString("MaxPax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NQuotes.
        /// </summary>
        public static string NQuotes {
            get {
                return ResourceManager.GetString("NQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        public static string Please_select {
            get {
                return ResourceManager.GetString("Please_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service.
        /// </summary>
        public static string Select_Service {
            get {
                return ResourceManager.GetString("Select_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service Rates.
        /// </summary>
        public static string Select_Service_Rates {
            get {
                return ResourceManager.GetString("Select_Service_Rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string Service_Details {
            get {
                return ResourceManager.GetString("Service_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Id.
        /// </summary>
        public static string Service_Id {
            get {
                return ResourceManager.GetString("Service_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        public static string Service_Name {
            get {
                return ResourceManager.GetString("Service_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Rates.
        /// </summary>
        public static string Service_Rates {
            get {
                return ResourceManager.GetString("Service_Rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsd.
        /// </summary>
        public static string Tsd {
            get {
                return ResourceManager.GetString("Tsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsi.
        /// </summary>
        public static string Tsi {
            get {
                return ResourceManager.GetString("Tsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsu.
        /// </summary>
        public static string Tsu {
            get {
                return ResourceManager.GetString("Tsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerNum.
        /// </summary>
        public static string VerNum {
            get {
                return ResourceManager.GetString("VerNum", resourceCulture);
            }
        }
    }
}
